### ISSUE TITLE
Create a method to update mongoDB generic account information for user

### ISSUE THREAD

**Issue by ginywiny** [mostafaboustani/Soen-341#19]
Currently index.js has a generic method to specify which account is used to reference the mongoDB database.

`"mongodb+srv://<username>:<password>@cluster0-pf0b2.mongodb.net/test?retryWrites=true&w=majority";`

Should find a way to generate username and password automatically for a new user without having to hard code it with the user's personal mongoDB account.

**Comment by gregtuc** [comment]
Closing as per commit that changed database access structure (JSON file named default that holds credentials)
