### ISSUE TITLE
* Unfollow Users

### ISSUE THREAD

**Issue by loganmcmullen** [mostafaboustani/Soen-341#27]
As a user I would like to be able to unfollow users so that I don't have to see their content.

1. Create x button next to each username under "following list"
2. Backend api to delete node from user.following.node
3. Sends confirm receipt status 200 with page refresh

Confirmation:
Is there a button to unfollow a user? Does the user no longer see me as a follower? Is this user no longer displayed as somebody I am following?

**Comment by gregtuc** [comment]
Users have an "unfollow" button next to the usernames in the Following list, the server route that accepts requests for this action removes the user from the list of accounts the active user is following in "following.js", and valid requests consistently send a status 200 response when the active user requests to unfollow an account. Thus, closing this issue.
