### ISSUE TITLE
* News Feed Page

### ISSUE THREAD

**Issue by loganmcmullen** [mostafaboustani/Soen-341#34]
As a user I would like to have a view so that I can see the accounts I follow exclusively.

1. Create "feed" component
2. Send fetch request to get most recent photo from each user followed (backend api loop (get user.following.photos.photo_n))
3. Front end display results

Confirmation:
Does the main page display recent uploads from the users I am following? Are the pictures displayed only from the accounts I am following? Does the main page display all pictures from the accounts since I have started following them?

**Comment by gregtuc** [comment]
1) On the home page (path = "/"), there exists a homepage component. 2) When the react component mounts, a request fetches all of the accounts that the active user is following. This array of users is used to fetch the latest photo that they have uploaded, and retrieve the file name. 3) Using this file name, the front end is able to make a POST request for each file and display all of the results on the news feed. Thus, closing the issue.
