### ISSUE TITLE
* User Bio Section

### ISSUE THREAD

**Issue by cottonswab** [mostafaboustani/Soen-341#39]
As a user I would like to have a view of my user description (bio page) so that I can add or modify the description.

1. Create test fields for each information of the user
2. Create " save bio" button
3. API to send post request to endpoint /api/updatebio (changes user.bio)

Confirmation:
Can I see the user description? Can another account see the user description? Does the user description take a text? Is there text size limit to the description?

**Comment by gregtuc** [comment]
1) On their personal profile, there exists a bio field in the account information section. Users have access to a button called "edit profile information" that opens a modal. This open lets you update your bio. 2) There exists a "update bio" button that will take your input and send it to the server at route "/api/updatebio". 3) After posting to the server, the active user's document is updated with the new bio information and the react component reflects this change when pulling in account information. Thus, closing the issue.
