### ISSUE TITLE
* Log in/log out to personal account

### ISSUE THREAD

**Issue by cottonswab** [mostafaboustani/Soen-341#51]
As a user I would like to be able to log in to and log out of my personal account so that I can differentiate my experience from other users

1. Use the JSON Web Token that gets sent after log-in to keep a user logged in
2. Have a button that plain and simple turns an image into binary (or similar) and then sends it to the server in the form of an array. Use whatever package necessary to make this happen
3. Have a profile page that sends a GET request to localhost:8000/api/currentuser. A response with all of a users info will be returned. You should display this information in a nice format

Confirmation:
Can I create my own account? Can I log into my own account? Can I see my account name?

**Comment by loganmcmullen** [comment]
Greg has implemented this feature @gregtuc please confirm and close this issue
