### ISSUE TITLE
* Search Users

### ISSUE THREAD

**Issue by cottonswab** [mostafaboustani/Soen-341#52]
As a user I would like to be able to search for other users so that I can find new pictures.

1. Create "search bar" text field with search button (See:https://react-bootstrap.github.io/components/navbar/)
2. Create "search results" component
3. API to send search request using get request with axios findAll method in mongoDB send JSON response with an array of all users

Confirmation:
Is there a search bar? Can I use the search bar to find a user? Does the search bar display the potential users? Does the search bar redirect me to the user's profile page?

**Comment by loganmcmullen** [comment]
Searching for users feature implemented
