### ISSUE TITLE
Button to modify description for picture

### ISSUE THREAD

**Issue by ginywiny** [mostafaboustani/Soen-341#76]
As a user I want to be able to edit the description for a picture I have posted so that I can change what I have written later on.

1. Add picture description edit button
2. Add text box to write in new description
3. Add save button to save written text

Confirmation: 
1. Button is displayed. 
2. Text box is displayed after clicking on edit button
3. Save button is displayed next to text box
4. Save button closes text box and new text is displayed next to picture

**Comment by loganmcmullen** [comment]
Button has been implemented
